#! /bin/bash
set -e #stop at first error

COMMIT_HASH=$(git rev-parse --verify HEAD --short)
COMMIT_INFO=$(git show HEAD --no-patch --pretty=format:'author: [%an, %ae] msg: %s')
COMMIT_NR=$(git rev-list HEAD --count)

docker build -f Dockerfile -t sharas/nettest:${COMMIT_HASH}  -t sharas/nettest:${COMMIT_NR} \
	--build-arg COMMIT_INFO="${COMMIT_INFO}" \
	--build-arg COMMIT_HASH="${COMMIT_HASH}" \
	--build-arg COMMIT_NR="${COMMIT_NR}" \
	.
